# Deploy Pods in Kubernetes Cluster
k run pod-nginx --image=nginx:latest -o yaml --dry-run=client > pod.yaml

apiVersion: v1
kind: Pod
metadata: 
 name: pod-ngnix
 app: nginx_app
spec:
  containers:
    - name: nginx-container
      image: nginx:latest

# Deploy Applications with Kubernetes Deployments
# Setup Kubernetes Namespaces and PODs

# Set Resource Limits in Kubernetes Pods

k apply -f- <<EOF
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpd-pod
  name: httpd-pod
spec:
  containers:
  - image: httpd:latest
    name: httpd-container
    resources:
      requests:
        memory: "15Mi"
        cpu: "100m"
      limits:
        memory: "20Mi"
        cpu: "100m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
EOF

k describe po httpd-pod | grep -A 5 -i Limits:

# Execute Rolling Updates in Kubernetes
k describe deployments.apps/nginx-deployment
k set image deployments.apps nginx-deployment nginx-container=nginx:1.17
k get po
k describe deployments.apps/nginx-deployment | grep -i image

# Revert Deployment to Previous Version in Kubernetes
k describe deployments.apps/nginx-deployment | grep -i revision
k rollout history deployment/nginx-deployment
k rollout history deployment/nginx-deployment --revision=1
k rollout undo deployment/nginx-deployment

# Deploy ReplicaSet in Kubernetes Cluster
### https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx_app
    type: front-end
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx_app
      type: front-end
  template:
    metadata:
      labels:
        app: nginx_app
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest

k get all