# Deploy Pods in Kubernetes Cluster
k run pod-nginx --image=nginx:latest -o yaml --dry-run=client > pod.yaml

apiVersion: v1
kind: Pod
metadata: 
 name: pod-ngnix
 app: nginx_app
spec:
  containers:
    - name: nginx-container
      image: nginx:latest

# Deploy Applications with Kubernetes Deployments
# Setup Kubernetes Namespaces and PODs

# Set Resource Limits in Kubernetes Pods

k apply -f- <<EOF
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpd-pod
  name: httpd-pod
spec:
  containers:
  - image: httpd:latest
    name: httpd-container
    resources:
      requests:
        memory: "15Mi"
        cpu: "100m"
      limits:
        memory: "20Mi"
        cpu: "100m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
EOF

k describe po httpd-pod | grep -A 5 -i Limits:

# Execute Rolling Updates in Kubernetes
k describe deployments.apps/nginx-deployment
k set image deployments.apps nginx-deployment nginx-container=nginx:1.17
k get po
k describe deployments.apps/nginx-deployment | grep -i image

# Revert Deployment to Previous Version in Kubernetes
k describe deployments.apps/nginx-deployment | grep -i revision
k rollout history deployment/nginx-deployment
k rollout history deployment/nginx-deployment --revision=1
k rollout undo deployment/nginx-deployment

# Deploy ReplicaSet in Kubernetes Cluster
### https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx_app
    type: front-end
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx_app
      type: front-end
  template:
    metadata:
      labels:
        app: nginx_app
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest

k get all

# Schedule Cronjobs in Kubernetes
k create cronjob devops --image=httpd:latest --schedule="*/8 * * * *" \
  -o yaml --dry-run=client > cronjob.yaml

apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: devops
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: devops
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: httpd:latest
            name: cron-devops
            command: ["sh", "-c", "echo", "Welcome to xfusioncorp!"]
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/8 * * * *' # The job then repeats this 8-minute loop for every hour of every day.
status: {}

# Create Countdown Job in Kubernetes
k create job countdown-datacenter --image=ubuntu:latest -o yaml --dry-run=client > job.yaml
vi job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: countdown-devops
spec:
  template:
    metadata:
      name: countdown-devops
      creationTimestamp: null
    spec:
      containers:
      - image: fedora:latest
        name: container-countdown-devops
        command: ["sleep"]
        args: ["5"]
        resources: {}
      restartPolicy: Never
status: {}

k create -f job.yaml
k get job

# Set Up Time Check Pod in Kubernetes
k create ns nautilus
k -n nautilus run time-check --image=busybox:latest -o yaml --dry-run=client > pod.yaml
k -n nautilus create cm time-config --from-literal=TIME_FREQ=7

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
  namespace: nautilus
spec:
  volumes:
    - name: log-volume
      hostPath:
        path: /opt/finance/time
        type: DirectoryOrCreate
  containers:
  - image: busybox:latest
    name: time-check
    command: ["/bin/sh", "-c"]
    args: ["while true; do date >> /opt/finance/time/time-check.log; sleep $TIME_FREQ; done"]
    env:
      - name: TIME_FREQ
        valueFrom:
          configMapKeyRef:
            name: time-config
            key: TIME_FREQ
    volumeMounts:
      - name: log-volume
        mountPath: /opt/finance/time
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# Resolve POD Deployemnt Issue
k edit pod webserver
nginx:latest

# Update Deployment and Service in Kubernetes
k get all
k edit svc nginx-service
k scale deployment/nginx-deployment --replicas=5
k set image deployment.apps/nginx-deployment nginx-container=nginx:latest
k describe deployments.apps/nginx-deployment