############## Creating a cluster with kubeadm ###########################
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
https://v1-34.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

# SSH to nodes
ssh controlplan
ssh node-summer

# Check default route
ip a | grep -A 2 -i enp1s0

# 2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
#     link/ether 0e:3e:86:a2:2e:53 brd ff:ff:ff:ff:ff:ff
#     inet 172.30.1.2/24 brd 172.30.1.255 scope global dynamic noprefixroute enp1s0
#        valid_lft 86312404sec preferred_lft 75523204sec
#     inet6 fe80::af29:7440:c8bc:fb7b/64 scope link 

ip route show
### default via 172.30.1.1 dev enp1s0 proto dhcp src 172.30.1.2 metric 1002 mtu 1500

cat /etc/hosts

# 127.0.0.1 localhost
# # The following lines are desirable for IPv6 capable hosts
# ::1 ip6-localhost ip6-loopback
# fe00::0 ip6-localnet
# ff00::0 ip6-mcastprefix
# ff02::1 ip6-allnodes
# ff02::2 ip6-allrouters
# ff02::3 ip6-allhosts
# 127.0.0.1 ubuntu
# 127.0.0.1 host01
# 127.0.0.1 controlplane
# 172.30.2.2 node01
# 172.30.2.2 node-summer

# kernel and OS version
uname -r && cat /etc/*release*

# Unique MAC address or product ID
ip link
or
ifconfig -a

### controlplane
# 2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
#     link/ether 8e:54:64:2d:6e:2f brd ff:ff:ff:ff:ff:ff

### node-summer
# 2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
#     link/ether 16:23:bd:d3:98:5b brd ff:ff:ff:ff:ff:ff

### product ID
sudo cat /sys/class/dmi/id/product_uuid

# Kube-API port NOT opened before install
nc 127.0.0.1 6443 -zv -w 2
ss -lnt | grep 6443

# Container Runtime Interface (CRI) - If you don't specify a runtime, kubeadm automatically tries to detect an installed container runtime by scanning through a list of known endpoints.
crictl ps
docker version

ls -l /var/run/containerd/containerd.sock
ls -l /var/run/crio/crio.sock
ls -l /var/run/cri-dockerd.sock

systemctl status containerd
systemctl status docker
systemctl status crio
systemctl status cri-dockerd

ss -lx | grep containerd

# Kubeadm & kubectl installed with the right version?
kubeadm version
k version


# init
kubeadm init -h

kubeadm init --kubernetes-version=1.34.1 \
--pod-network-cidr 192.168.0.0/16 \
--ignore-preflight-errors=NumCPU \
--ignore-preflight-errors=Mem

# joint worker node
kubeadm join 172.30.1.2:6443 --token xxx \
        --discovery-token-ca-cert-hash sha256:xxxxx

or

kubeadm token create --print-join-command
ssh node-summer
kubeadm join 172.30.1.2:6443 --token ...
exit

# move config file
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

# check nodes and k8s version
k get nodes
kubectl get pod -A