https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

k get nodes
k version
k describe nodes controlplane | grep -i "Kubelet Version"
kubeadm version

# Verifying if the Kubernetes package repositories are used with the right version
pager /etc/apt/sources.list.d/kubernetes.list


# List kubeadm versions
sudo apt update
sudo apt-cache madison kubeadm
apt-cache show kubeadm
VERSION=1.34.3-1.1

# Install kubeadm
sudo apt-mark unhold kubeadm && \
sudo apt-get update && sudo apt-get install -y kubeadm=$VERSION && \
sudo apt-mark hold kubeadm

# Upgrade K8s (will renew certs if version is same)
sudo kubeadm upgrade plan
K_VERSION=${VERSION%%-*}
kubeadm upgrade apply v$K_VERSION

# Upgrade kubectl and kubelet
apt-get install kubectl=$VERSION kubelet=$VERSION -y
service kubelet restart

# On worker as well
ssh node01
VERSION=1.34.3-1.1
apt-get install kubectl=$VERSION kubelet=$VERSION -y
service kubelet restart