# Step 1: Install and Configure Helm Repository
helm version
helm repo add nginx-stable https://helm.nginx.com/stable
helm repo update

helm repo list
helm search repo nginx

helm show chart nginx-stable/nginx-ingress
helm show values nginx-stable/nginx-ingress


# Step 2: Install Application Using Helm Chart
kubectl create namespace nginx-ingress
helm install my-nginx-ingress nginx-stable/nginx-ingress  \
  --namespace nginx-ingress   --set controller.replicaCount=2  \
  --set controller.service.type=NodePort \
  --set controller.service.httpPort.nodePort=30080 \
  --set controller.service.httpsPort.nodePort=30443
helm install my-nginx-ingress nginx-stable/nginx-ingress   --namespace nginx-ingress   --set controller.replicaCount=2   --set controller.service.type=NodePort   --set controller.service.httpPort.nodePort=30080   --set controller.service.httpsPort.nodePort=30443

helm list -A
kubectl get pods -n nginx-ingress
kubectl get svc -n nginx-ingress
helm history my-nginx-ingress -n nginx-ingress
helm get manifest my-nginx-ingress -n nginx-ingress

# Step 3: Upgrade Release with Custom Values
cat /root/nginx-values.yaml
helm upgrade my-nginx-ingress nginx-stable/nginx-ingress \
  --namespace nginx-ingress \
  --values /root/nginx-values.yaml
helm upgrade my-nginx-ingress nginx-stable/nginx-ingress \
  --namespace nginx-ingress \
  --values /root/nginx-values.yaml \
  --set controller.service.annotations."service\.kubernetes\.io/load-balancer-source-ranges"="10.0.0.0/8"
helm status my-nginx-ingress -n nginx-ingress
helm history my-nginx-ingress -n nginx-ingress
kubectl get pods -n nginx-ingress
kubectl describe deployment -n nginx-ingress

# Step 4: Rollback and Troubleshoot
helm upgrade my-nginx-ingress nginx-stable/nginx-ingress \
  --namespace nginx-ingress \
  --set controller.image.tag="invalid-tag" \
  --set controller.replicaCount=5

kubectl get pods -n nginx-ingress -w
helm history my-nginx-ingress -n nginx-
helm rollback my-nginx-ingress 3 -n nginx-ingress
helm status my-nginx-ingress -n nginx-ingress
kubectl get pods -n nginx-ingress
helm get values my-nginx-ingress -n nginx-ingress
helm get all my-nginx-ingress -n nginx-ingress